### ISSUE TITLE
메인페이지 - 추천/카테고리/신규 강좌

### ISSUE THREAD

**Issue by yuheejin** [SiSt-ProjectTeam/CultureCenter#1]
## Description
메인페이지 추천/카테고리/신규 강좌 출력

## To-do
- [x]  강좌 조회 sql
- [x]  강좌 조회 ajax 처리
- [x]  강좌 클릭 시, 상세 페이지로 이동

## ETC
- 카테고리/신규 강좌 : 로그인 시, 관심지점의 강좌 조회
- 강좌 상태가 접수중인 강좌는 장바구니 추가 버튼 보이기
