### ISSUE TITLE
수강내역 - 수강 내역 조회

### ISSUE THREAD

**Issue by yuheejin** [SiSt-ProjectTeam/CultureCenter#11]
## Description
수강/취소 내역 목록 조회

## To-do
- [x]  tiles 처리
- [x] 마이페이지 → 수강내역 : 페이지 이동
- [x] 수강내역 리스트 출력 : ajax
- [x] ajax 응답 인코딩 처리
- [x]  수강내역 리스트 조회 sql
- [x] 주문번호/강좌명 검색, 연도/학기 필터 적용

## ETC
|**요청**|요청방식|컨트롤러|응답|
|:-:|:-:|:-:|:-:|
|/mypage/atlct/list.do|Get|MypageAtlctController|/mypage/atlct/list.jsp|
|/mypage/atlct/list.ajax|Post|MypageAtlctController|ResponseEntity\<String\>|

1. ajax가 반환하는 html 인코딩 깨짐 문제 발생 => 매핑 어노테이션에 반환 데이터타입 지정하여 해결
   - 참고 블로그 : [[Spring] consumes와 produces의 차이](https://mungto.tistory.com/438#)

2. 오류 415 Unsupported MediaType in Spring Application 
   - JSON형식이 아닌 데이터를 `@RequestBody`로 받으려하여 발생한 오류
   - fcn.frmAjax()에서 jQuery 객체를 JSON 으로 파싱하여 해결
   - 기존코드 
      ~~~
            jQuery.ajax({
                url: url,
                type: "post",
                timeout: 30000,
                data: $(formObj).serializeArray(),
                dataType: dataType,
                async: sync,
                cache: false,
                beforeSend: function() {
                    if (loading) {
                        fnc.startProgress(jQuery("#dimdBg"));
                    }
                },
                success: function(data, status, xhr) {
                    if (callbackAjax) {
                        callbackAjax(data);
                    }
                },
                error: function(e) {
                    if (e.status == 403) {
                        if (confirm("자동 로그아웃 처리되었습니다. 로그인을 다시 시도해주세요.")) {
                            //moveLoginPage();
                        }
                    } else {}
                },
                complete: function() {
                    if (loading) {
                        fnc.endProgress(jQuery("#dimdBg"));
                    }
                    submitFlag = false;
                }
            });
      ~~~
   - 수정한 코드
      ~~~
            // 폼 데이터를 배열로 가져오기	
            var formDataArray = $(formObj).serializeArray();
			
            // 배열을 객체로 변환
            var formDataObject = {};
            $.each(formDataArray, function(i, field) {
		formDataObject[field.name] = field.value;
            });
			
            // JSON 형식으로 변환
            var jsonData = JSON.stringify(formDataObject);
			
            jQuery.ajax({
                url: url,
                type: "post",
                timeout: 30000,
                data: jsonData,
                contentType : "application/json; charset=utf-8",
                dataType: dataType,
                async: sync,
                cache: false,
                beforeSend: function() {
                    if (loading) {
                        fnc.startProgress(jQuery("#dimdBg"));
                    }
                },
                success: function(data, status, xhr) {
                    debugger;
                    if (callbackAjax) {
                        callbackAjax(data);
                    }
                },
                error: function(e) {
                    if (e.status == 403) {
                        if (confirm("자동 로그아웃 처리되었습니다. 로그인을 다시 시도해주세요.")) {
                            //moveLoginPage();
                        }
                    } else {}
                },
                complete: function() {
                    if (loading) {
                        fnc.endProgress(jQuery("#dimdBg"));
                    }
                    submitFlag = false;
                }
            });
      ~~~
