### ISSUE TITLE
step2 할인,결제수단,총결제금액, 기타버튼

### ISSUE THREAD

**Issue by P-JHo** [SiSt-ProjectTeam/CultureCenter#124]
## Description
할인, 결제수단, 총결제금액 관련 기능 구현 \

## To-do
- [x]  할인수단선택 버튼
- [ ]  할인혜택(L.point) 사용관련 기능
- [x]  결제수단 선택 기능
- [x]  주문내역 확인동의의 "보기"
- [x]  이전 버튼
- [x]  총 결제금액 띄우기 
## ETC
할인수단 구현 X ( 원래 사이트도 구현 안함 (disabled처리) )
결제수단 : 무조건 CARD
할인혜택 : 우리 테이블의 Point관련 사용!

**Comment by P-JHo** [comment]
할인 미구현
