### ISSUE TITLE
step2 -> step3

### ISSUE THREAD

**Issue by P-JHo** [SiSt-ProjectTeam/CultureCenter#125]
## Description
수강결제2페이지에서 3페이지 이동 구현

## To-do
- [x]  NicePay API 기능 구현
- [x]  뒤로가기 기능 구현
- [x]  수강결제 버튼 클릭시 주문, 수강내역 테이블에 추가
- [x]  수강결제 취소 클릭시 ajax 주문,수강내역테이블 삭제
- [x]  수강결제 완료시 주문테이블에 TID 추가 

## ETC
주문테이블 수정 : tid컬럼 추가 ( DB, 테이블명세서만 수정완료 / exerd,erd 수정.. )

**Comment by P-JHo** [comment]
NicePayAPI/v1이 아닌 v3로 구현함 ( Iframe과 controller에서 직접 로직을 구현하기 위해 js가 아닌 form태그로 Nicepay API를 사용하기 위함 )
 * MID(판매자ID)와 MerchantKey는 NicePay의 Test버젼 아이디,키를 사용함 
1. Iframe에 구현시 security에 의해 Deny되는 에러 발생 
 => iframe이 다른 페이지를 포함하다보니 XSS공격에 취약함, 따라서 security 적용시 Access자체가 거부됨
 => 해결방법 : security의 설정에 http의 header가 같은 origin이면 iframe을 허용해주는 SOP설정을 해주면 됨
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/292b6568-29e4-4c51-9ad7-ea47acc59692)
참고자료 : 
https://computer-science-student.tistory.com/497
https://studystorage.blogspot.com/2017/02/iframe-1_26.html

2. 인증사의 결제인증 진행시 DTO를 통해 매개변수를 받으니 MID를 받아오지 못하는 문제가 발생
 => 해결방법 : Map으로 받음
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/40b190cb-c961-4a4c-bcce-231b612bbd1f)

3. Nicepay의 결제인증을 받을시 위변조검증을 위한 무결성 검증Data의 값을 주고받아 이를 Service에서 맞는지 확인하고 맞지 않다면 결제를 진행(서버승인)하지 않는 처리를 해야함
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/1befa6b2-de0d-46c2-ab8e-3d5679cb856f) 

4. 인증절차 및 개념, 매개변수의 정의와 처리해야할 로직은 v3의 docs 참고( https://developers.nicepay.co.kr/manual-auth.php )
**컨트롤러**
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/473f6003-252f-438e-adf7-d92c08c265f5)

**Comment by P-JHo** [comment]
**7. 승인까지 모두 완료 후  step3로  iframe에서 부모창의 form태그를 submit**
=> 해결방법 : window.parent 쿼리로 부모창 호출
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/4caa7c8e-3883-49a4-8de5-cc216c1c6829)

**Comment by P-JHo** [comment]
**8. 코드가 길어지며 컨트롤러가 무거워지는 일이 발생**
=> 해결방법 :  service를 여러번 호출하는 코드를 complexService를 만들어 대체
( 모듈화! )
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/50e587b5-497d-4185-96da-b2f79e6917b3)
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/2f0b297e-ddfb-445e-8e50-ef0ee4a9b0b6)

**Comment by P-JHo** [comment]
**10. 결제취소시 js의 ajax가 실행안되는 오류 발생**
iframe에서 ajax가 실행안됨 -> script로 첨부된 js파일의 함수를 실행하지 못함(ajax만..)
iframe상에서 ajax실행시 오류발생.. ( 완벽한 오류 이해하지 못함 )
=> 해결법 : script에 직접 ajax 호출
but! post로 ajax호출시 시큐리티에서 access deny동일한 오류발생
meta태그에 csrf생성시켜서 ajax의 header부분에 넣어줘도 역시나 access deny
=> 해결법 : 우선 GET방식으로 요청..

**Comment by P-JHo** [comment]
**11. 결제 모두 완료하고 step3로 이동시 시큐리티 url정규화 문제발생**
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
=> 해결법 :

**Comment by P-JHo** [comment]
**12. ajax나 retTemplate의 요청 url에 절대경로로 도메인이 localhost인 경우**
서버에 배포하거나 다른 ip로 접속시 오류가 발생함! 
해결 => 상대경로로 수정 
/ localhost가 아니라 외부API or 외부링크 사용이 아니라면 모두 상대경로를 줘야함!
