### ISSUE TITLE
수강내역 - 내역 상세 조회

### ISSUE THREAD

**Issue by yuheejin** [SiSt-ProjectTeam/CultureCenter#14]
## Description
수강(주문)내역에 대한 상세 정보 조회

## To-do
- [x]  수강 내역 클릭시, 주문 상세 페이지로 이동
- [x]  상세 페이지 정보 조회 sql
- [x]  상세 페이지 출력
- [x]  강좌명 클릭시, 강좌 상세 페이지로 이동

## ETC
|**요청**|요청방식|컨트롤러|응답|
|:-:|:-:|:-:|:-:|
|/mypage/atlct/view.do|Get|MypageAtlctController|/mypage/atlct/view.jsp|
