### ISSUE TITLE
메인페이지 - 공지사항/이벤트

### ISSUE THREAD

**Issue by yuheejin** [SiSt-ProjectTeam/CultureCenter#2]
## Description
메인페이지 공지사항/이벤트 출력 및 페이지 이동

## To-do
- [ ]  공지사항/이벤트 조회 sql
- [ ]  메인페이지 공지사항/이벤트 출력
- [ ]  클릭 시, 상세페이지로 이동

## ETC
공지사항/이벤트 내용 출력시, html 적용이 안된 텍스트로 출력
