### ISSUE TITLE
메인페이지 - 마이페이지 조회

### ISSUE THREAD

**Issue by yuheejin** [SiSt-ProjectTeam/CultureCenter#22]
## Description
마이페이지 조회

## To-do
- [x]  로그인 상태일 경우, header에 보이기
- [x] 링크 클릭시 마이페이지 정보 조회 sql
- [x]  마이페이지 정보 출력

## ETC
|**요청**|요청방식|컨트롤러|응답|
|:-:|:-:|:-:|:-:|
|/mypage/member/count.ajax|Get|MypageMemberController|ResponseEntity\<String\>|
