### ISSUE TITLE
이용안내 - 지점 조회

### ISSUE THREAD

**Issue by haeyng** [SiSt-ProjectTeam/CultureCenter#28]
## Description
이용안내 - 지점 안내  카테고리의 지점 조회 기능 

## To-do
- [x]  지점 조회 sql
- [x]  지점 정보(주소, 전화번호, 강의실이름) 조회 sql
- [x]  지점 사진
- [x]  지점 소분류 클릭시 사진, 지점 정보, 지도 Ajax
