### ISSUE TITLE
이용안내 - 강사지원 step1 개인정보 수집 동의

### ISSUE THREAD

**Issue by haeyng** [SiSt-ProjectTeam/CultureCenter#31]
## Description
이용안내 - 강사지원 카테고리의 강사 지원 신청 기능 구현
강사지원 step1 개인정보 수집 동의 -> step2 신청서 입력페이지 이동

## To-do
- [x] 강사 신청서 dto 추가
- [x] 개인정보 수집 동의 여부 Ajax
- [x] 강사신청 버튼 클릭시 개인정보 수집 동의 여부 페이지 이동
- [x] 개인정보 수집 동의시 step2 신청서 페이지로 이동

## ETC
개인정보 동의 및 제출 STEP 1 -> 2 -> 3 중  step 1 , 2
로그인 여부 체크 X
