### ISSUE TITLE
회원정보변경 - 회원 정보 차량정보, 동반 수강자 정보

### ISSUE THREAD

**Issue by SungJun545412** [SiSt-ProjectTeam/CultureCenter#48]
## Description
회원정보변경 - 회원 정보 차량정보, 동반 수강자 정보 추가, 삭제

## To-do
- [ ]  세선에 저장된 값으로 차량정보 DB에 UPDATE
- [ ]  세선에 저장된 값으로 동반 수강자 DB에  DELETE
- [ ]  자녀회원 추가 모달창 정보 입력 DB에 INSERT
