### ISSUE TITLE
강좌 검색 - 지점으로 찾기

### ISSUE THREAD

**Issue by gseoo** [SiSt-ProjectTeam/CultureCenter#53]
## Description
header에서 수강신청에 mouseover > 강좌검색 클릭한 화면 > 지점으로 찾기

## To-do
- [ ] DB에 있는 지점 출력 구현
- [ ] 지점으로 찾기 클릭 시 type=branch로 파라미터값 넘어가도록 구현
- [ ] 지점ID 파라미터로 넘어가도록 구현

## ETC
