### ISSUE TITLE
강좌 검색 - 강좌로 찾기

### ISSUE THREAD

**Issue by gseoo** [SiSt-ProjectTeam/CultureCenter#54]
## Description
header에서 수강신청에 mouseover > 강좌검색 클릭한 화면 > 강좌로 찾기

## To-do
- [x]  DB에 있는 강좌 카테고리 출력 구현
- [x]  강좌로 찾기 클릭 시 type=category로 파라미터값 넘어가도록 구현
- [x] 대분류·중분류·소분류 코드 파라미터로 넘어가도록 구현
