### ISSUE TITLE
동반수강자정보 목록,등록,삭제 처리

### ISSUE THREAD

**Issue by P-JHo** [SiSt-ProjectTeam/CultureCenter#89]
## Description
동반수강자정보 목록,등록,삭제 처리

## To-do
- [x]  동반수강자 정보 띄우기 ( 없을때도 )
- [x]  동반수강자 자녀회원 추가하기(ㄹㅇ추가됨)
- [x]  동반수강자 삭제(ㄹㅇ삭제됨)
- [x]  수강자 변경/추가 처리

**Comment by P-JHo** [comment]
동반 수강자 삭제시 발생한 issue
Ajax요청을 처리할 컨트롤러메서드의 인자로 @RequstBody int children_sq 를 했을때 오류가 발생함
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/81a25b9f-5625-43c1-b0d9-3f0f9439a049)
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/6ceb34ad-dcc3-4680-be0f-70f8b777ae82)
위 오류는 json데이터형식을 @Requestbody가 해석할때 
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/1a6d21e8-0bc0-48b8-b297-62dbcaebfe15)
위의 설명과 같이 http요청의 body에 담긴 json데이터를 가져와 resolver를 거쳐 파라미터로 들어가있는 객체에서 json의 key값(name)에 해당하는 getter를 가져와 맵핑을 하여 데이터를 바인딩하는 구조로 이루어져있음!
json데이터는 일종의 직렬화되어 보내지는 String형식임(직렬화와 json은 다름!)
 이를 @RequestBody가 역직렬화(deserialize)를 함(오류내용) 즉, 위의 맵핑을 하려면 역직렬화가 가능한 자바의 "객체"여야함 이때, Map은 Json데이터형식의 객체와 매우 흡사한 구조를 가짐
 key:value 따라서 Map이나 Collection으로 객체를 대신하여 받을 수 있음!

결론 JsonData를 파라미터로 받을땐 자바객체 or Map,Collection을 사용해야한다.
참고 : 
https://jwdeveloper.tistory.com/306
https://batory.tistory.com/469
https://velog.io/@namda-on/JavaScript-Map-%EA%B3%BC-Object-%EC%9D%98-%EC%B0%A8%EC%9D%B4
https://velog.io/@oneook/%EB%B2%88%EC%97%AD-%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-Map%EC%9D%84-Object-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC%ED%95%A0-%EB%95%8C%EB%8A%94-%EC%96%B8%EC%A0%9C%EC%9D%BC%EA%B9%8C%EC%9A%94

**Comment by P-JHo** [comment]
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/43389774-fc56-497c-8f8d-304d89dcc631)
