### ISSUE TITLE
수강자변경

### ISSUE THREAD

**Issue by P-JHo** [SiSt-ProjectTeam/CultureCenter#90]
## Description
수강정보의 수강자 기능구현

## To-do
- [x]  수강자 목록띄우기(본인)
- [x]  수강자 변경/추가 목록 띄우기
- [x]  수강자 변경(저장하기)시 목록 구현
- [x]  영유아,아동강좌의 경우 수강자변경/추가가 아니라 자녀회원 선택으로 띄우기
- [x]  자녀회원 선택 기능 구현

**Comment by P-JHo** [comment]
강좌가 영유아,아동강좌의 경우 수강자변경,추가가 아닌 자녀회원선택으로 뜸
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/e57febea-738d-46c0-b478-6dd07024e520)

**Comment by P-JHo** [comment]
**수강자 변경시**
js에 
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/f39a96c8-9af2-49f2-b181-b0f38f6c0ad8)
의 해석
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/7bb62171-1c73-4dd4-8884-a9679e621343)
첫번째로 보내지는 태그의 dataset 을 불러옴
![image](https://github.com/SiSt-ProjectTeam/CultureCenter/assets/141379702/2f9b41f8-486a-48d9-a4bf-f3b8040652dd)
$().data("param") == html.dataset.param 인 이유!
