### ISSUE TITLE
강좌 상세 보기 - 수강신청

### ISSUE THREAD

**Issue by gseoo** [SiSt-ProjectTeam/CultureCenter#93]
## Description
수강신청 버튼일 때, 해당 버튼 클릭한 후 화면 구현 - 결제창 넘어가는 것까지 구현

## To-do
- [x] 강좌 정보 가져오는 쿼리문 작성
- [x]  상세 보기 페이지 내 화면 구현
- [x]  결제창으로 넘어가는 과정 구현
